DevFestProject/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'DevFestProject.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^', include('application.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

application/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings

urlpatterns = patterns('',
    url(r'^$', 'application.views.home'),
    url(r'^dashboard$', 'application.views.dashboard'),
    url(r'^signin$', 'application.views.sign_in'),
    url(r'^signup$', 'application.views.signup'),
    url(r'^signup2$', 'application.views.signup2'),
    url(r'^logout$', 'application.views.user_logout'),
    url(r'^addcourse$', 'application.views.add_course_view'),
    url(r'^courses$', 'application.views.courses'),
    url(r'^course/(?P<id>\d+)/$', 'application.views._course'),
    url(r'^add_assignment$', 'application.views.add_assignment_view'),
    url(r'^submit_assignment$', 'application.views.submit_assignment_view'),
    url(r'^register_course$', 'application.views.register_course_view'),
    url(r'^teachers$', 'application.views.view_teachers'),
    url(r'^askquestion$', 'application.views.ask_question_view'),
    url(r'^replyquestion$', 'application.views.reply_question_view'),
    url(r'^mail_box$','application.views.mail_box_view'),
    url(r'^messageview$', 'application.views.show_messageview'),
    url(r'^rate$', 'application.views.rate_the_question'),
    url(r'^markassignment$', 'application.views.mark_assignment'),
    url(r'^search_course$', 'application.views.courses_search_view'),
    url(r'^upload_notes$', 'application.views.upload_notes'),
    url(r'^search_teachers$', 'application.views.search_teachers_view'),
    url(r'^add_quiz', 'application.views.create_Quiz'),
    url(r'^quiz/(?P<id>\d+)/', 'application.views.take_quiz')
)

urlpatterns += patterns('',
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT,
    }),
)

application/models.py
from django.db import models
import datetime
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
# Create your models here.

class UserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        now = datetime.datetime.now()
        if not email:
            raise ValueError('The given email address must be set')
        email = UserManager.normalize_email(email)
        user = self.model(email=email,
                          is_staff=False, is_active=True, is_superuser=False,
                          last_login=now, date_joined=now, **extra_fields)

        user.set_password(password)
        user.full_name = user.first_name + user.last_name
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password, **extra_fields):
        u = self.create_user(email, password, **extra_fields)
        u.is_staff = True
        u.is_active = True
        u.is_superuser = True
        u.save(using=self._db)
        return u


class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField('email address', unique=True)
    first_name = models.CharField('first name', max_length=30)
    last_name = models.CharField('last name', max_length=30)
    is_staff = models.BooleanField('staff status', default=False)
    is_active = models.BooleanField('active', default=True)
    is_email_verified = models.BooleanField('verified', default=False)
    county_choices = (
        ('Pakistan', 'Pakistan'),
        ('India', 'India'),
        ('Afghanistan', 'Afghanistan')
    )
    country = models.CharField(max_length=1000, choices=county_choices)
    postal_code = models.IntegerField(blank=True, null=True)
    user_type_choices = (

        ('Teacher', 'Teacher'),
        ('Student', 'Student'),
    )
    user_type = models.CharField(max_length=50, choices=user_type_choices)
    USERNAME_FIELD = 'email'
    date_joined = models.DateTimeField(default=datetime.datetime.now())
    profile_pic = models.ImageField(upload_to="uploads", default="uploads/default_profile.jpg")


    objects = UserManager()

    def get_full_name(self):
        return u' '.join((self.first_name, self.last_name))

    def get_short_name(self):
        return u' '(self.first_name)


class student(models.Model):
    user_id = models.ForeignKey('User')
    School_University = models.CharField(max_length=300, blank=False, null=False)
    Age = models.CharField(max_length=10, default='18+')
    Date_of_Birth = models.CharField(max_length=50, blank=True, null=True)


class teacher(models.Model):
    user_id = models.ForeignKey('User')
    most_recent_job_title = models.CharField(max_length=1000)
    major_subjects = (
        ('', '-'),
        ('Accounting', 'Accounting'),
        ('Math', 'Math'),
    )

    subjects = models.CharField(choices=major_subjects, max_length=1000)


class course (models.Model):
    name = models.CharField(max_length=1000)
    code = models.CharField(max_length=15, unique=True)
    description = models.TextField(max_length=10000)
    taughtby = models.ForeignKey(User)
    coursepic = models.ImageField(upload_to="uploads", default="uploads/default_profile.jpg", null=True)


class assignment(models.Model):
    title = models.CharField(max_length=1000)
    description = models.TextField()
    weightage = models.IntegerField(null=False)
    document = models.FileField(upload_to='uploads', null=True)


class course_assignment(models.Model):
    course_id = models.ForeignKey('course')
    assignment_id = models.ForeignKey('assignment')


class course_student(models.Model):
    course_id = models.ForeignKey('course')
    student_id = models.ForeignKey('User')


class assignment_submission(models.Model):
    assignment_id = models.ForeignKey('assignment')
    student_id = models.ForeignKey('User')
    submission_file = models.FileField(upload_to='uploads', null=False)
    marks = models.IntegerField(blank=True, null=True)


class questionsession (models.Model):
    askedby = models.ForeignKey('User',related_name='askedby')
    askedfrom = models.ForeignKey('User',related_name='askedfrom')
    ratingofstudent = models.IntegerField(blank=True, null=True)
    ratingofteacher = models.IntegerField(blank=True, null=True)
    firstmessage = models.TextField()

class message (models.Model):
    askedby = models.ForeignKey('User', related_name='askedby1')
    askedfrom = models.ForeignKey('User', related_name='askedfrom1')
    mess = models.TextField()

class questionsmessages (models.Model):
    question_id = models.ForeignKey('questionsession')
    message_id = models.ForeignKey('message')


class notes(models.Model):
    which_course = models.ForeignKey('course')
    noteFile = models.FileField(upload_to='uploads')


class quizz(models.Model):
    weightage = models.IntegerField(blank=True, null=True)
    title = models.CharField(max_length=1000)
    belongs_to = models.ForeignKey('course')

class MCQ (models.Model):
    quizz_id = models.ForeignKey('quizz')
    question = models.CharField(max_length=1000)
    option1 = models.CharField(max_length=1000)
    option2 = models.CharField(max_length=1000)
    option3 = models.CharField(max_length=1000)
    option4 = models.CharField(max_length=1000)
    correct_answer = models.IntegerField(blank=True, null=True)
    user_answer = models.IntegerField(blank=True, null=True)


class marked_quiz(models.Model):
    marks = models.IntegerField(blank=True, null=True)
    of_whom = models.ForeignKey('User')
    quizid = models.ForeignKey('quizz')

application/views.py
from django.shortcuts import render_to_response, render
from application.forms import UserCreationForm, UserCreationForm2, LoginForm, add_course, add_assignment
from django.core.context_processors import csrf
from django.http import HttpResponseRedirect, HttpResponse
from django.template import RequestContext
from django.contrib.auth import authenticate, login, logout
from application.models import User, course, assignment, \
    course_assignment, assignment_submission, course_student, teacher, questionsession, questionsmessages, message, notes, MCQ, quizz, marked_quiz
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from itertools import izip
import random


def home(request):
    a = course.objects.all()[:3]
    args = {}
    args['courses_1'] = a[0]
    args['courses_2'] = a[1]
    args['courses_3'] = a[2]
    return render(request, 'home.html', args)


def dashboard(request):
    if request.user.user_type == "Student":
        courseStudent = course_student.objects.filter(student_id=request.user.id)
        allCourses = []
        for c in courseStudent:
            allCourses.append(course.objects.filter(id=c.course_id.id)[0])

        assignmentofthisuser = assignment_submission.objects.filter(student_id = request.user)
        marks = {}

        for k in allCourses:
            total_marks=0
            obtained_marks=0
            weightage=0
            course_assignment1 = course_assignment.objects.filter(course_id = k.id)
            for j in course_assignment1:
                for g in assignmentofthisuser:
                    if g.assignment_id == j.assignment_id:
                        if j is not None and g and g.marks:
                            obtained_marks = int(obtained_marks) + int(g.marks)
                            total_marks = total_marks + 10
                            weightage = weightage + j.assignment_id.weightage

            marks[k.id] = ((obtained_marks/total_marks)*weightage)

        args = {}
        args['all_courses'] = allCourses
        args['all_marks'] = marks
    else:
        allCourses = course.objects.filter(taughtby=request.user)
        args = {}
        args['all_courses'] = allCourses
    return render(request, 'dashboard.html', args)


def sign_in(request):
    if request.user.is_authenticated():
        return HttpResponseRedirect('/dashboard')
    else:
        args = {}
        args.update(csrf(request))
        if request.method == 'POST':
            form = LoginForm(request.POST)
            if form.is_valid():
                user = authenticate(username=request.POST["username"], password=request.POST["password"])
                if user is not None:
                    if user.is_active:
                        login(request, user)
                        return HttpResponseRedirect('/dashboard')
                    else:
                        args['myErrors'] = "User Not Activated."
                else:
                    args['myErrors'] = "Username or passwords Don't match."
        else:
            form = LoginForm()

        args['form'] = form
        return render_to_response('signin.html', args, RequestContext(request))


def signup(request):
    if request.user.is_authenticated():
        return HttpResponseRedirect('/dashboard')
    else:
        if request.method == 'POST':
            form = UserCreationForm(request.POST)
            if request.POST['password'] != request.POST['confirm_password']:
                args = {}
                args.update(csrf(request))
                args['password_error'] = 'Passwords donot match'
                args['form'] = form
                return render_to_response('signup.html', args, RequestContext(request))
            if form.is_valid():
                form.save()
                user = authenticate(username=request.POST['email'], password=request.POST['password'])
                if user is not None:
                    if user.is_active:
                        login(request, user)
                        request.user.save()
                    else:
                        return "not activated"
                else:
                    return HttpResponse("<h1>User Cannot be authenticated</h1>")
                args = {}
                args.update(csrf(request))
                args['form'] = UserCreationForm2()

                return HttpResponseRedirect("/signup2", args)
        else:
            form = UserCreationForm()

        args = {}
        args.update(csrf(request))
        args['form'] = form
        return render_to_response('signup.html', args)


@login_required()
def signup2(request):
    if request.method == 'POST':
        form = UserCreationForm2(request.POST)
        if form.is_valid():
            form.save(request.user)
            return HttpResponseRedirect('/dashboard')
    else:
        form = UserCreationForm2()

    args = {}
    args.update(csrf(request))
    args['form'] = form
    return render_to_response('signup2.html', args, RequestContext(request))


@login_required()
def user_logout(request):
    logout(request)
    return HttpResponseRedirect('/', RequestContext(request))



@login_required()
def add_course_view(request):

    args = {}
    args.update(csrf(request))


    if request.user.is_authenticated():
        if request.user.user_type == 'Teacher':
            if request.method =='POST':
                form = add_course(request.POST, request.FILES)
                if form.is_valid():
                    currentcourse = course()
                    currentcourse.name = request.POST['name']
                    currentcourse.code = request.POST['code']
                    currentcourse.description = request.POST['description']
                    currentcourse.coursepic= request.FILES['coursepic']

                    currentcourse.taughtby = request.user

                    currentcourse.save()
                    return HttpResponseRedirect('/dashboard')
                else:
                    args['form'] = form
                    return render_to_response('addcourse.html', args, RequestContext(request))
            else:
                form = add_course()
                args['form'] = form
                return render_to_response('addcourse.html', args, RequestContext(request))

        else:
            return HttpResponse("You are not allowed to access this Page <a href="/">Go Back</a>")
    else:
        return HttpResponseRedirect('/home',RequestContext(request))


def courses(request):
    all_courses = course.objects.all()
    args = {}
    args['courses'] = all_courses
    return render(request, 'courses.html', args)


def _course(request, id=None):
    corse = course.objects.filter(id=id)
    if corse:
        args = {}
        args['course'] = corse[0]
        assignments_c = course_assignment.objects.filter(course_id=corse[0])
        assignments = []
        for a in assignments_c:
            assignments.append(a.assignment_id)
        args['assignments'] = assignments
        alreay_registered = False
        all_students = course_student.objects.all()
        for s in all_students:
            if s.student_id == request.user and s.course_id == corse[0]:
                alreay_registered = True
        allnotes = notes.objects.filter(which_course=corse[0])
        args['notes'] = allnotes

        args['alreay_registered'] = alreay_registered

        args['quizes'] = quizz.objects.filter(belongs_to=corse)
    else:
        return HttpResponseRedirect('/courses')

    return render_to_response('course.html', args, RequestContext(request))



def add_assignment_view(request):
    args = {}
    args.update(csrf(request))
    if request.user.is_authenticated():
        if request.user.user_type == 'Teacher':
            if request.method =='POST':
                form = add_assignment(request.POST, request.FILES)
                if form.is_valid():
                    currentassignment = assignment()
                    currentassignment.title = request.POST['title']
                    currentassignment.description = request.POST['description']
                    currentassignment.weightage = request.POST['weightage']
                    currentassignment.document = request.FILES['document']
                    c = course.objects.filter(id=request.POST['name'])
                    currentassignment.save()
                    ass = course_assignment()
                    ass.course_id = c[0]
                    ass.assignment_id = currentassignment
                    ass.save()

                    return HttpResponseRedirect('/courses')
                else:
                    args['form'] = form

                    return render_to_response('addassignment.html', args, RequestContext(request))
            else:
                form = add_assignment()
                args['form'] = form
                co = course.objects.filter(taughtby=request.user)
                if not co:
                    return HttpResponseRedirect('/dashboard')
                args['courses'] = co
                return render_to_response('addassignment.html', args, RequestContext(request))
        else:
            return HttpResponse("You are not allowed to access this Page <a href="/">Go Back</a>")
    else:
        return HttpResponseRedirect('/home',RequestContext(request))


def submit_assignment_view(request):
    if request.method == "POST":
        a_s = assignment_submission()
        ass = assignment.objects.filter(id=request.POST['assignment'])
        a_s.assignment_id = ass[0]
        a_s.student_id = request.user
        a_s.submission_file = request.FILES['submission_file']
        a_s.save()
        return HttpResponseRedirect('/dashboard')


def register_course_view(request):
    c = course_student()
    c.student_id = request.user
    c.course_id = course.objects.filter(id=request.POST['register'])[0]
    c.save()
    return HttpResponseRedirect('/dashboard')

application/templates/addassignment.html
{% extends "master.html" %}


{% block header %}

{% endblock %}

{% block middle %}

{% endblock %}

{% block middle_second %}

 <div class="container">
    <div class="row middle-margin" >
        <div class="col-xs-12">
            <div class="row ">
                <div class="col-xs-10 ">
                    <form action="/add_assignment" enctype="multipart/form-data" method="post">{% csrf_token %}
                <label>Course Name</label>
                <div>
                    <select id="id_name" name="name" class="form-control input-lg">
                        {% for c in courses %}
                            <option value="{{ c.id }}">{{ c.name }} ( {{ c.code }} )</option>
                        {% endfor %}
                    </select>
                </div>
                <label>Title</label>
                <div>
                    <span id="couse-description-error" class="error">{{ form.title.errors }}</span>
                    <input name="title" class="form-control input-lg" type="text" />
                </div>
                <label>Description</label>
                <div>
                    <span id="couse-description-error" class="error">{{ form.title.errors }}</span>
                    <textarea name="description" rows="6" class="form-control input-lg"  ></textarea>
                </div>
                <label>Weightage</label>
                <div>
                    <span id="couse-description-error" class="error">{{ form.weightage.errors }}</span>
                    <input name="weightage" class="form-control input-lg" type="text" />
                </div>
                <br>
                <div>
                    <span id="couse-image-error" class="error">{{ form.document.errors }}</span>
                    <input name="document" class=" form-control input-jg" type="file" value="Choose Image" />
                </div>
                 <div id="submit-button">
                     <button class="btn btn-lg expand btn-primary" type="submit" value="Add">Add</button>
                 </div>
            </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block footer %}
{% endblock %}

application/templates/addcourse.html
{% extends "master.html" %}


{% block header %}

{% endblock %}

{% block middle %}

{% endblock %}

{% block middle_second %}

 <div class="container">
    <div class="row middle-margin" >
        <div class="col-xs-12">
            <div class="row ">
                <div class="col-xs-10 ">
                    <form action="/addcourse" enctype="multipart/form-data" method="post">{% csrf_token %}
                <label>Course Name</label>
                <div>
                    <span id="course-name-error" class="error">{{ form.name.errors }}</span>
                    <input id="id_name" name="name" class="form-control input-lg" type="text" value="" />
                </div>
                <label>Course Code</label>
                <div>
                    <span id="course-code-error" class="error">{{ form.code.errors }}</span>
                    <input name="code" class="form-control input-lg " type="text" />
                </div>
                <label>Description</label>
                <div>
                    <span id="couse-description-error" class="error">{{ form.description.errors }}</span>
                    <textarea name="description" rows="10" class="form-control input-lg" type="text" ></textarea>
                </div>
                        <br>
                <div>
                    <span id="couse-image-error" class="error">{{ form.coursepic.errors }}</span>
                    <input name="coursepic" class=" form-control input-jg" type="file" value="Choose Image" />
                </div>
                 <div id="submit-button">
                     <button class="btn btn-lg expand btn-primary" type="submit" value="Add">Add</button>
                 </div>
            </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block footer %}
{% endblock %}

application/templates/askquestion.html
{% extends "master.html" %}


{% block header %}

{% endblock %}

{% block middle %}

{% endblock %}

{% block middle_second %}

 <div class="container">
    <div class="row middle-margin" >
        <div class="col-xs-12">
            <div class="row ">

                 <div class="col-xs-10 ">
                     <form action="/askquestion" enctype="multipart/form-data" method="post">{% csrf_token %}
                        <label>Send TO</label>
                         <input type='hidden' name='sentid' value={{ sentid  }}> </input>
                        <label> {{ sentname }}</label>
                        <label>Type your message</label>
                        <div>
                            <textarea name="messagetext" rows="10" class="form-control input-lg" type="text" ></textarea>
                        </div>
                                <br>

                         <div id="submit-button">
                             <button class="btn btn-lg expand btn-primary" type="submit" value="Add">Send</button>
                         </div>
                     </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block footer %}
{% endblock %}

application/templates/course.html
{% extends "master.html" %}


{% block header %}

{% endblock %}

{% block middle %}

{% endblock %}

{% block middle_second %}

 <div class="container">
    <div class="row middle-margin " >

        <div class="col-lg-8 col-md-10 col-sm-12 col-xs-12">
            <div class="text-center bottom-border">
                <h2>{{ course.name }}</h2>
            </div>
            <div class="course bottom-border " style="margin-bottom: 10px;padding-bottom: 20px;">
                <div class="row">
                  <div class="col-xs-12 col-md-4 hidden-sm hidden-xs">
                      <img data-src="holder.js/200x200" class="" alt="200x200" src="/media/{{ course.coursepic }}" style="width: 200px; height: 200px;">
                      <br><br>
                      {% if user.user_type == "Student" and not alreay_registered %}
                      <div class="row">
                        <div class="col-xs-8 col-xs-offset-3">
                            <form action="/register_course" method="post">{% csrf_token %}
                                <button name="register" type="submit" value="{{ course.id }}" class="btn btn-primary ">Register</button>
                            </form>
                        </div>
                      </div>
                      {% endif %}
                  </div>
                  <div class="col-xs-12 col-xs-offset-2 col-sm-8 col-sm-offset-4 hidden-lg hidden-md">
                        <img data-src="holder.js/200x200" class="" alt="200x200" src="/media/{{ course.coursepic }}" style="width: 200px; height: 200px;">
                        <br><br>
                      {% if user.user_type == "Student" and not alreay_registered  %}
                      <div class="row">
                        <div class="col-xs-8 col-xs-offset-3">
                            <form action="/register_course" method="post">{% csrf_token %}
                                <button name="register" type="submit" value="{{ course.id }}" class="btn btn-primary ">Register</button>
                            </form>
                        </div>
                      </div>
                      {% endif %}
                  </div>
                  <div class="col-xs-12 col-md-8 col-sm-12">
                      <b><span>{{ course.taughtby.get_full_name }}</span></b><b><span class="text-primary pull-right">{{ course.code }}</span></b>
                      <br><br>
                      <div class="text-left bottom-border" style="padding-bottom: 20px">
                        <span>{{ course.description }}</span>
                      </div>
                  </div>


                  <div class="col-xs-12 col-md-8 col-sm-12">
                      <b><span>Assignments</span></b>
                      <br>

                      <div class="text-left"  >
                        {% for assignment in assignments %}
                        <div class="name-box panel-body" style="margin-bottom: 10px;">
                            <h4>{{ assignment.title }}</h4>
                            <p>{{ assignment.description }}</p>
                            <p class="text-primary"><b>{{ assignment.weightage }}</b></p>
                            <a target="_blank" href="/media/{{ assignment.document }}">{{ assignment.document }}</a>
                            {% if user.user_type == "Student" %}
                            <br><br>
                            <div>
                                <form action="/submit_assignment" enctype="multipart/form-data" method="post">{% csrf_token %}
                                    <input name="submission_file" class="input-sm" type="FILE">
                                    <button name="assignment" value="{{ assignment.id }}" class="btn-primary btn btn-sm" type="submit">Submit</button>
                                </form>
                            </div>
                            {% endif %}
                            {% if course.taughtby.user_type == 'Teacher'%}
                            {% if course.taughtby.id == user.id  %}
                            <a class="pull-right btn-primary btn btn-sm" href="/markassignment?assignmentid={{ assignment.id }}">Mark</a>
                            <div class="clearfix"></div>
                            {% endif %}
                            {% endif %}
                        </div>
                        {% endfor %}
                      </div>

                      <br><br>
                      <b><span>Notes</span></b>
                      <br>

                      <div class="text-left"  >
                        <div class="name-box panel-body" style="margin-bottom: 10px;">
                            {% for note in notes %}
                                <p><a href="/media/{{ note.noteFile }}">{{ note.noteFile }}</a></p>
                            {% endfor %}
                            <p></p>
                            <form action="/upload_notes" enctype="multipart/form-data" method="post"> {% csrf_token %}
                                <input name="note_file" type="file" class="form-control input-sm" />
                                <input name="which_course" type="hidden" value="{{ course.id }}" />
                                <button class="pull-right btn btn-primary btn-sm" type="submit">upload</button>
                                <div class="clearfix"></div>
                            </form>

                        </div>

                      <br><br>
                      <b><span>Quiz</span></b>
                      <br>

                       <div class="text-left"  >
                        <div class="name-box panel-body" style="margin-bottom: 10px;">
                            {% for quiz in quizes %}
                                <p><a href="/quiz/{{ quiz.id }}">{{ quiz.title }}</a></p>
                            {% endfor %}
                            <p></p>


                        </div>

                      </div>

                  </div>


                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block footer %}
{% endblock %}

application/templates/courses.html
{% extends "master.html" %}


{% block header %}

{% endblock %}

{% block middle %}

{% endblock %}

{% block middle_second %}

 <div class="container">
    <div class="row middle-margin " >
        <div class="col-lg-3 col-md-2 hidden-sm hidden-xs">
            <div class="row">
                <div class="col-xs-12 name-box panel-body">
                    <div class="text-center"><form action="/search_course" method="get"><input name="searchterm" class="form-control input-sm" placeholder="Hit Enter to Search" type="text"></form></div>
                </div>
            </div>
        </div>
        <div class="col-lg-8 col-md-10 col-sm-12 col-xs-12">
            <div class="text-center bottom-border">
                <h2>CURRENT COURSES</h2>
            </div>
            {% for course in courses %}
            <div class="course bottom-border " style="margin-bottom: 10px;padding-bottom: 20px;">
                <div class="row">
                  <div class="col-xs-12 col-md-4 hidden-sm hidden-xs">
                      <img data-src="holder.js/200x200" class="" alt="200x200" src="/media/{{ course.coursepic }}" style="width: 200px; height: 200px;">
                  </div>
                  <div class="col-xs-12 col-xs-offset-2 col-sm-8 col-sm-offset-4 hidden-lg hidden-md">
                        <img data-src="holder.js/200x200" class="" alt="200x200" src="/media/{{ course.coursepic }}" style="width: 200px; height: 200px;">
                  </div>
                  <div class="col-xs-12 col-md-8 col-sm-12">
                      <b><span class="pad-around">{{ course.taughtby.get_full_name }}</span></b>
                      <p><a class="text-primary" href="/course/{{ course.id }}"><h3>{{ course.name }}</h3></a></p>
                      <div class="text-left">
                        <span>{{ course.description }}</span>
                      </div>
                  </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}

{% block footer %}
{% endblock %}

application/templates/home.html
{% extends "master.html" %}